---
server:
  port: 8080
spring:
  messages: basename:validation
  application:
    name: Vanilla
  mvc:
    view:
      prefix: "/"
      suffix: ".jsp"
  jpa:
    hibernate:
      ddlAuto: create-drop
    show-sql: false
security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3
